### ISSUE TITLE
agent-daemonset fails livenessProbe

### ISSUE THREAD

**Issue by chuck-ecob** [spiffe/spire-tutorials#10]
I am running kubernetes `1.13.11-gke14` on GCP.

The livenessProbe as written fails with the following error:

```
  Warning  Unhealthy  5m46s (x11 over 15m)  kubelet, gke-spire-testing-default-pool-f304a191-tfjq  Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/opt/spire/bin/spire-agent healthcheck -socketPath /run/spire/sockets/agent.sock\": stat /opt/spire/bin/spire-agent healthcheck -socketPath /run/spire/sockets/agent.sock: no such file or directory": unknown
```

The proposed patch to the definition, which resolves this issue, is as follows:

```
diff --git a/k8s/agent-daemonset.yaml b/k8s/agent-daemonset.yaml
index dc00a4d..ba7c874 100644
--- a/k8s/agent-daemonset.yaml
+++ b/k8s/agent-daemonset.yaml
@@ -42,7 +42,10 @@ spec:
           livenessProbe:
             exec:
               command:
-                - /opt/spire/bin/spire-agent healthcheck -socketPath /run/spire/sockets/agent.sock
+                - /opt/spire/bin/spire-agent
+                - healthcheck
+                - -socketPath
+                - /run/spire/sockets/agent.sock
             failureThreshold: 2
             initialDelaySeconds: 15
             periodSeconds: 60
```

**Comment by evan2645** [comment]
Thank you @chuck-ecob! If you have a moment to open a PR, it would be very welcome

I also wonder if the behavior has changed somewhere along the line?

**Comment by chuck-ecob** [comment]
Here is a PR, though the CI seems to have failed on a step I'm unfamiliar with:

https://github.com/spiffe/spire-tutorials/pull/11

**Comment by chuck-ecob** [comment]
@evan2645 it seems the CI is failing, but on a portion that was not part of my change (spire-server). Unclear how I should proceed at this point, but am willing to chip in and assist where possible.

As for behaviour, the API for livenessProbe may have changed, but this usage meshes with v1.12 and later (sadly older docs no longer available)

**Comment by evan2645** [comment]
> it seems the CI is failing, but on a portion that was not part of my change (spire-server). Unclear how I should proceed at this point, but am willing to chip in and assist where possible.

I was able to replicate this error locally without including your change - I will look into it further

> As for behaviour, the API for livenessProbe may have changed, but this usage meshes with v1.12 and later (sadly older docs no longer available)

Sure, makes sense. Thanks again for the contribution

**Comment by evan2645** [comment]
Fixed in https://github.com/spiffe/spire-tutorials/pull/11

**Comment by bhavvu** [comment]
I still face the same issue, 

Error:  Warning  Unhealthy  47s (x3 over 2m47s)  kubelet, k8masterg1m1  Liveness probe failed: Agent is unavailable.
  Normal   Killing    47s                  kubelet, k8masterg1m1  Container spire-agent failed liveness probe, will be restarted



cat agent.daemonset.yaml

          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/sockets/agent.sock
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3

**Comment by azdagron** [comment]
Hi @bhavvu! Can you obtain logs from the agent container? That will help us determine why the healthcheck is failing.

**Comment by bhavvu** [comment]
I am not getting any logs from kubectl logs <pod_name>, only in the evnts I am getting the this information.

Error: Warning Unhealthy 47s (x3 over 2m47s) kubelet, k8masterg1m1 Liveness probe failed: Agent is unavailable.
Normal Killing 47s kubelet, k8masterg1m1 Container spire-agent failed liveness probe, will be restarted

**Comment by azdagron** [comment]
Do you mind sharing your agent.conf?

**Comment by bhavvu** [comment]
@azdagron 
This is my agent.conf
[root@k8masterg1m1 ..2020_03_12_15_57_53.613224381]# cat agent.conf
agent {
  data_dir = "/run/spire"
  log_level = "DEBUG"
  server_address = "spire-server"
  server_port = "8081"
  socket_path = "/run/spire/sockets/agent.sock"
  trust_bundle_path = "/run/spire/bundle/bundle.crt"
  trust_domain = "example.org"
}

plugins {
  NodeAttestor "k8s_sat" {
    plugin_data {
      # NOTE: Change this to your cluster name
      cluster = "demo-cluster"
    }
  }

  KeyManager "memory" {
    plugin_data {
    }
  }

  WorkloadAttestor "k8s" {
    plugin_data {
      skip_kubelet_verification = true
    }
  }

  WorkloadAttestor "unix" {
      plugin_data {
      }
  }
}
